/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#b7c6ee",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e3e3de",
        "surface": "#faf9f4",
        "surface-container-highest": "#e3e3de",
        "primary-container": "#1b2a4a",
        "tertiary-fixed": "#a6f0e9",
        "secondary": "#835400",
        "inverse-on-surface": "#f2f1ec",
        "on-error": "#ffffff",
        "tertiary-container": "#00312e",
        "on-secondary-container": "#6e4600",
        "surface-bright": "#faf9f4",
        "surface-container-high": "#e9e8e3",
        "on-background": "#1b1c19",
        "tertiary-fixed-dim": "#8bd3cd",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#b7c6ee",
        "outline": "#75777f",
        "tertiary": "#001a19",
        "surface-tint": "#4f5e81",
        "on-secondary-fixed-variant": "#633f00",
        "on-surface-variant": "#45464e",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#0a1a3a",
        "outline-variant": "#c5c6cf",
        "surface-dim": "#dbdad5",
        "surface-container": "#efeee9",
        "on-secondary-fixed": "#2a1800",
        "error": "#ba1a1a",
        "on-tertiary-container": "#569e99",
        "on-tertiary-fixed": "#00201e",
        "secondary-container": "#fdb244",
        "on-primary": "#ffffff",
        "secondary-fixed": "#ffddb5",
        "on-primary-container": "#8392b7",
        "primary-fixed": "#d9e2ff",
        "secondary-fixed-dim": "#ffb956",
        "inverse-surface": "#30312e",
        "on-tertiary-fixed-variant": "#00504c",
        "on-surface": "#1b1c19",
        "background": "#faf9f4",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f5f4ef",
        "on-primary-fixed-variant": "#384668",
        "primary": "#041534",
      },
      borderRadius: { DEFAULT: "1rem", lg: "2rem", xl: "3rem", full: "9999px" },
      spacing: {
        "gutter-sm": "1rem",
        margin: "2rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        gutter: "1.5rem",
        "margin-sm": "1rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        "label-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "title-md": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "title-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["22px", { lineHeight: "30px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "title-lg": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
